-- LSPU Portal PostgreSQL schema for Supabase
-- Converted from db/lspu_portal_v2.68.sql
-- Source schema version: May 15, 2026

CREATE TYPE "admins_role_enum" AS ENUM ('Super Admin', 'Admin', 'Registrar');
CREATE TYPE "admins_status_enum" AS ENUM ('Active', 'Inactive');
CREATE TYPE "admission_info_campus_enum" AS ENUM ('Sta Cruz Campus', 'Siniloan Campus', 'San Pablo Campus', 'Los Banos Campus');
CREATE TYPE "admission_info_student_type_enum" AS ENUM ('College', 'GSaR', 'Post Graduate');
CREATE TYPE "admission_info_year_level_enum" AS ENUM ('1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year');
CREATE TYPE "applicants_application_status_enum" AS ENUM ('Pending', 'Draft', 'Submitted', 'Enrolled', 'Rejected');
CREATE TYPE "applicants_sex_enum" AS ENUM ('Male', 'Female');
CREATE TYPE "applicants_civil_status_enum" AS ENUM ('Single', 'Married', 'Widowed');
CREATE TYPE "applicants_first_generation_student_enum" AS ENUM ('Yes', 'No');
CREATE TYPE "applicant_status_log_status_enum" AS ENUM ('Pending', 'Draft', 'Submitted', 'Enrolled', 'Rejected');
CREATE TYPE "educational_background_elementary_type_enum" AS ENUM ('Public', 'Private');
CREATE TYPE "educational_background_high_school_type_enum" AS ENUM ('Public', 'Private');
CREATE TYPE "educational_background_senior_high_school_type_enum" AS ENUM ('Public', 'Private');
CREATE TYPE "educational_background_track_strand_enum" AS ENUM ('STEM', 'ABM', 'HUMSS', 'GAS', 'Home Economics', 'ICT', 'Agri-fishery Arts', 'Industrial Arts', 'Arts and Design Track', 'Sports Track');
CREATE TYPE "family_info_guardian_relationship_enum" AS ENUM ('Guardian', 'Father', 'Mother');
CREATE TYPE "semester_semester_name_enum" AS ENUM ('1st Semester', '2nd Semester', 'Inter Semester');
CREATE TYPE "semester_status_enum" AS ENUM ('Open', 'Closed');

CREATE TABLE "admins" (
  "admin_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" varchar(191) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "first_name" varchar(80) NOT NULL,
  "last_name" varchar(80) NOT NULL,
  "role" "admins_role_enum" NOT NULL DEFAULT 'Admin',
  "status" "admins_status_enum" NOT NULL DEFAULT 'Active',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "campus" (
  "Campus_Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Campus_Name" varchar(150) NOT NULL,
  "Barangay" varchar(100) DEFAULT NULL,
  "Municipality" varchar(100) DEFAULT NULL,
  "Province" varchar(100) DEFAULT NULL,
  "campus_email" varchar(255) DEFAULT NULL
);

CREATE TABLE "colleges" (
  "college_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "college_name" varchar(150) NOT NULL,
  "college_code" varchar(20) DEFAULT NULL,
  "college_email" varchar(255) DEFAULT NULL
);

CREATE TABLE "programs" (
  "Program_Code" varchar(20) NOT NULL,
  "Program_Name" varchar(120) NOT NULL,
  "college_id" integer NOT NULL
);

CREATE TABLE "semester" (
  "semester_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "semester_name" "semester_semester_name_enum" NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "status" "semester_status_enum" DEFAULT 'Open'
);

CREATE TABLE "year" (
  "year_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "academic_year" varchar(20) NOT NULL,
  "is_current" smallint DEFAULT 0
);

CREATE TABLE "subjects" (
  "Subject_Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "College_Id" integer DEFAULT NULL,
  "Subject_Code" varchar(255) DEFAULT NULL,
  "Subject_Name" varchar(255) DEFAULT NULL,
  "Credits" integer DEFAULT NULL
);

CREATE TABLE "section" (
  "section_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "section_name" varchar(50) NOT NULL,
  "program_code" varchar(20) NOT NULL,
  "year_level" integer NOT NULL,
  "campus_id" integer NOT NULL
);

CREATE TABLE "specializations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Program_Code" varchar(20) NOT NULL,
  "spec_code" varchar(20) NOT NULL,
  "spec_name" varchar(120) NOT NULL
);

CREATE TABLE "special_programs" (
  "special_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "college_id" integer DEFAULT NULL,
  "special_name" varchar(200) NOT NULL,
  "category" varchar(100) DEFAULT NULL
);

CREATE TABLE "applicants" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Email" varchar(180) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "application_status" "applicants_application_status_enum" NOT NULL DEFAULT 'Pending',
  "First_Name" varchar(80) NOT NULL,
  "Middle_Name" varchar(80) DEFAULT NULL,
  "Last_Name" varchar(80) NOT NULL,
  "Suffix" varchar(20) DEFAULT NULL,
  "Birthdate" date DEFAULT NULL,
  "Birth_Place" varchar(120) DEFAULT NULL,
  "Citizenship" varchar(80) DEFAULT NULL,
  "Sex" "applicants_sex_enum" DEFAULT NULL,
  "Civil_Status" "applicants_civil_status_enum" DEFAULT NULL,
  "Religion" varchar(80) DEFAULT NULL,
  "Disability" varchar(120) DEFAULT NULL,
  "First_Generation_Student" "applicants_first_generation_student_enum" DEFAULT NULL,
  "Contact_Number" varchar(15) DEFAULT NULL,
  "Landline_Number" varchar(20) DEFAULT NULL,
  "House_Number" varchar(20) DEFAULT NULL,
  "Street" varchar(100) DEFAULT NULL,
  "Barangay" varchar(80) DEFAULT NULL,
  "Municipality" varchar(80) DEFAULT NULL,
  "Province" varchar(80) DEFAULT NULL,
  "Zip_Code" varchar(10) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "admission_info" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "applicant_id" integer NOT NULL,
  "campus" "admission_info_campus_enum" NOT NULL,
  "student_type" "admission_info_student_type_enum" NOT NULL,
  "year_level" "admission_info_year_level_enum" NOT NULL,
  "admission_type" varchar(80) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "applicant_status_log" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "applicant_id" integer NOT NULL,
  "status" "applicant_status_log_status_enum" NOT NULL,
  "changed_by" varchar(80) NOT NULL DEFAULT 'admin',
  "changed_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "educational_background" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "applicant_id" integer NOT NULL,
  "elementary_school_name" varchar(150) DEFAULT NULL,
  "elementary_school_address" varchar(200) DEFAULT NULL,
  "elementary_type" "educational_background_elementary_type_enum" DEFAULT NULL,
  "elementary_year_from" smallint DEFAULT NULL,
  "elementary_year_to" smallint DEFAULT NULL,
  "high_school_name" varchar(150) DEFAULT NULL,
  "high_school_address" varchar(200) DEFAULT NULL,
  "high_school_type" "educational_background_high_school_type_enum" DEFAULT NULL,
  "high_school_year_from" smallint DEFAULT NULL,
  "high_school_year_to" smallint DEFAULT NULL,
  "senior_high_school_name" varchar(150) DEFAULT NULL,
  "senior_high_school_address" varchar(200) DEFAULT NULL,
  "senior_high_school_type" "educational_background_senior_high_school_type_enum" DEFAULT NULL,
  "senior_high_school_year_from" smallint DEFAULT NULL,
  "senior_high_school_year_to" smallint DEFAULT NULL,
  "track_strand" "educational_background_track_strand_enum" DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "family_info" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "applicant_id" integer NOT NULL,
  "guardian_first_name" varchar(80) DEFAULT NULL,
  "guardian_last_name" varchar(80) DEFAULT NULL,
  "guardian_contact_number" varchar(15) DEFAULT NULL,
  "guardian_email" varchar(180) DEFAULT NULL,
  "guardian_relationship" "family_info_guardian_relationship_enum" DEFAULT NULL,
  "guardian_barangay" varchar(80) DEFAULT NULL,
  "guardian_municipality" varchar(80) DEFAULT NULL,
  "guardian_province" varchar(80) DEFAULT NULL,
  "father_first_name" varchar(80) DEFAULT NULL,
  "father_middle_name" varchar(80) DEFAULT NULL,
  "father_last_name" varchar(80) DEFAULT NULL,
  "father_age" smallint DEFAULT NULL,
  "father_citizenship" varchar(80) DEFAULT NULL,
  "father_educational_attainment" varchar(60) DEFAULT NULL,
  "father_employment_status" varchar(80) DEFAULT NULL,
  "father_occupation" varchar(120) DEFAULT NULL,
  "mother_first_name" varchar(80) DEFAULT NULL,
  "mother_middle_name" varchar(80) DEFAULT NULL,
  "mother_last_name" varchar(80) DEFAULT NULL,
  "mother_age" smallint DEFAULT NULL,
  "mother_citizenship" varchar(80) DEFAULT NULL,
  "mother_educational_attainment" varchar(60) DEFAULT NULL,
  "mother_employment_status" varchar(80) DEFAULT NULL,
  "mother_occupation" varchar(120) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "intended_course" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "applicant_id" integer NOT NULL,
  "Program_Code" varchar(20) NOT NULL,
  "Specialization" varchar(20) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "students" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "student_id" varchar(20) NOT NULL,
  "applicant_id" integer DEFAULT NULL,
  "first_name" varchar(100) DEFAULT NULL,
  "middle_name" varchar(100) DEFAULT NULL,
  "last_name" varchar(100) DEFAULT NULL,
  "suffix" varchar(20) DEFAULT NULL,
  "email" varchar(191) DEFAULT NULL,
  "contact_number" varchar(30) DEFAULT NULL,
  "program_code" varchar(20) DEFAULT NULL,
  "campus" varchar(80) DEFAULT NULL,
  "year_level" varchar(20) DEFAULT NULL,
  "section_id" integer DEFAULT NULL,
  "semester_id" integer DEFAULT NULL,
  "Enrollment_Date" date DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "Status" varchar(50) DEFAULT 'Active'
);

CREATE TABLE "instructors" (
  "Instructor_ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Last_Name" varchar(100) NOT NULL,
  "First_Name" varchar(100) NOT NULL,
  "Middle_Name" varchar(50) DEFAULT NULL,
  "Suffix_Title" varchar(50) DEFAULT NULL,
  "Degree" varchar(50) DEFAULT NULL,
  "Subject_ID" integer DEFAULT NULL,
  "College_ID" integer DEFAULT NULL,
  "Campus_ID" integer DEFAULT NULL
);

CREATE TABLE "enrollment" (
  "enrollment_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "student_id" integer NOT NULL,
  "section_id" integer NOT NULL,
  "semester_id" integer NOT NULL,
  "year_id" integer NOT NULL,
  "enrollment_date" date NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'Enrolled'
);

CREATE TABLE "enrolled_subjects" (
  "enrolled_subject_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "enrollment_id" integer NOT NULL,
  "subject_id" integer NOT NULL,
  "instructor_id" integer DEFAULT NULL,
  "status" varchar(20) DEFAULT 'Enrolled'
);

CREATE TABLE "grades" (
  "grade_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "enrolled_subject_id" integer NOT NULL,
  "class_engagement" decimal(5,2) DEFAULT NULL,
  "learning_outputs" decimal(5,2) DEFAULT NULL,
  "quizzes" decimal(5,2) DEFAULT NULL,
  "midterm" decimal(5,2) DEFAULT NULL,
  "final" decimal(5,2) DEFAULT NULL,
  "total" numeric(5,2) GENERATED ALWAYS AS (
    COALESCE("class_engagement", 0) * 0.20 +
    COALESCE("learning_outputs", 0) * 0.20 +
    COALESCE("quizzes", 0) * 0.20 +
    COALESCE("midterm", 0) * 0.20 +
    COALESCE("final", 0) * 0.20
  ) STORED,
  "final_grade" varchar(10) GENERATED ALWAYS AS (
    CASE
      WHEN "class_engagement" IS NULL OR "learning_outputs" IS NULL OR "quizzes" IS NULL OR "midterm" IS NULL OR "final" IS NULL THEN NULL
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 99 THEN '1.00'
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 96 THEN '1.25'
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 93 THEN '1.50'
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 90 THEN '1.75'
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 87 THEN '2.00'
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 84 THEN '2.25'
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 81 THEN '2.50'
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 78 THEN '2.75'
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 75 THEN '3.00'
      WHEN ("class_engagement" + "learning_outputs" + "quizzes" + "midterm" + "final") / 5 >= 70 THEN '4.0'
      ELSE '5.0'
    END
  ) STORED,
  "remarks" varchar(50) DEFAULT NULL
);

CREATE TABLE "payment" (
  "payment_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "student_id" integer NOT NULL,
  "semester_id" integer NOT NULL,
  "year_id" integer NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "payment_date" date NOT NULL,
  "payment_method" varchar(50) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'Pending'
);

CREATE TABLE "receipt" (
  "receipt_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "payment_id" integer NOT NULL,
  "receipt_number" varchar(50) NOT NULL,
  "issued_date" date NOT NULL
);

CREATE TABLE "schedule" (
  "schedule_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "subject_id" integer NOT NULL,
  "instructor_id" integer NOT NULL,
  "section_id" integer NOT NULL,
  "semester_id" integer NOT NULL,
  "year_id" integer NOT NULL,
  "day" varchar(20) NOT NULL,
  "time_start" time NOT NULL,
  "time_end" time NOT NULL,
  "room" varchar(50) DEFAULT NULL
);




