CREATE TABLE public.portal_otps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purpose text NOT NULL CHECK (purpose IN ('register', 'reset')),
    email text NOT NULL,
    code_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    verified_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX portal_otps_lookup_idx
ON public.portal_otps (purpose, email, expires_at DESC);

ALTER TABLE public.portal_otps ENABLE ROW LEVEL SECURITY;
