-- LSPU Portal PostgreSQL constraints and indexes
-- Converted from db/lspu_portal_v2.68.sql

ALTER TABLE "admins" ADD CONSTRAINT "admins_pkey" PRIMARY KEY ("admin_id");
ALTER TABLE "campus" ADD CONSTRAINT "campus_pkey" PRIMARY KEY ("Campus_Id");
ALTER TABLE "colleges" ADD CONSTRAINT "colleges_pkey" PRIMARY KEY ("college_id");
ALTER TABLE "programs" ADD CONSTRAINT "programs_pkey" PRIMARY KEY ("Program_Code");
ALTER TABLE "semester" ADD CONSTRAINT "semester_pkey" PRIMARY KEY ("semester_id");
ALTER TABLE "year" ADD CONSTRAINT "year_pkey" PRIMARY KEY ("year_id");
ALTER TABLE "subjects" ADD CONSTRAINT "subjects_pkey" PRIMARY KEY ("Subject_Id");
ALTER TABLE "section" ADD CONSTRAINT "section_pkey" PRIMARY KEY ("section_id");
ALTER TABLE "specializations" ADD CONSTRAINT "specializations_pkey" PRIMARY KEY ("id");
ALTER TABLE "special_programs" ADD CONSTRAINT "special_programs_pkey" PRIMARY KEY ("special_id");
ALTER TABLE "applicants" ADD CONSTRAINT "applicants_pkey" PRIMARY KEY ("id");
ALTER TABLE "admission_info" ADD CONSTRAINT "admission_info_pkey" PRIMARY KEY ("id");
ALTER TABLE "applicant_status_log" ADD CONSTRAINT "applicant_status_log_pkey" PRIMARY KEY ("id");
ALTER TABLE "educational_background" ADD CONSTRAINT "educational_background_pkey" PRIMARY KEY ("id");
ALTER TABLE "family_info" ADD CONSTRAINT "family_info_pkey" PRIMARY KEY ("id");
ALTER TABLE "intended_course" ADD CONSTRAINT "intended_course_pkey" PRIMARY KEY ("id");
ALTER TABLE "students" ADD CONSTRAINT "students_pkey" PRIMARY KEY ("id");
ALTER TABLE "instructors" ADD CONSTRAINT "instructors_pkey" PRIMARY KEY ("Instructor_ID");
ALTER TABLE "enrollment" ADD CONSTRAINT "enrollment_pkey" PRIMARY KEY ("enrollment_id");
ALTER TABLE "enrolled_subjects" ADD CONSTRAINT "enrolled_subjects_pkey" PRIMARY KEY ("enrolled_subject_id");
ALTER TABLE "grades" ADD CONSTRAINT "grades_pkey" PRIMARY KEY ("grade_id");
ALTER TABLE "payment" ADD CONSTRAINT "payment_pkey" PRIMARY KEY ("payment_id");
ALTER TABLE "receipt" ADD CONSTRAINT "receipt_pkey" PRIMARY KEY ("receipt_id");
ALTER TABLE "schedule" ADD CONSTRAINT "schedule_pkey" PRIMARY KEY ("schedule_id");
ALTER TABLE "admission_info" ADD CONSTRAINT "uq_admission_applicant" UNIQUE ("applicant_id");
ALTER TABLE "applicants" ADD CONSTRAINT "uq_applicant_email" UNIQUE ("Email");
ALTER TABLE "educational_background" ADD CONSTRAINT "uq_edubg_applicant" UNIQUE ("applicant_id");
ALTER TABLE "family_info" ADD CONSTRAINT "uq_family_applicant" UNIQUE ("applicant_id");
ALTER TABLE "intended_course" ADD CONSTRAINT "uq_intended_applicant" UNIQUE ("applicant_id");
ALTER TABLE "receipt" ADD CONSTRAINT "uq_receipt_payment" UNIQUE ("payment_id");
ALTER TABLE "students" ADD CONSTRAINT "uq_student_id" UNIQUE ("student_id");

CREATE INDEX "idx_ai_applicant" ON "admission_info" ("applicant_id");
CREATE INDEX "idx_applicant" ON "applicant_status_log" ("applicant_id");
CREATE INDEX "idx_eb_applicant" ON "educational_background" ("applicant_id");
CREATE INDEX "idx_es_enrollment" ON "enrolled_subjects" ("enrollment_id");
CREATE INDEX "idx_es_subject" ON "enrolled_subjects" ("subject_id");
CREATE INDEX "idx_es_instructor" ON "enrolled_subjects" ("instructor_id");
CREATE INDEX "idx_enr_student" ON "enrollment" ("student_id");
CREATE INDEX "idx_enr_section" ON "enrollment" ("section_id");
CREATE INDEX "idx_enr_semester" ON "enrollment" ("semester_id");
CREATE INDEX "idx_enr_year" ON "enrollment" ("year_id");
CREATE INDEX "idx_fi_applicant" ON "family_info" ("applicant_id");
CREATE INDEX "idx_gr_enrolled_subject" ON "grades" ("enrolled_subject_id");
CREATE INDEX "idx_inst_subject" ON "instructors" ("Subject_ID");
CREATE INDEX "idx_inst_college" ON "instructors" ("College_ID");
CREATE INDEX "idx_inst_campus" ON "instructors" ("Campus_ID");
CREATE INDEX "idx_ic_applicant" ON "intended_course" ("applicant_id");
CREATE INDEX "idx_ic_program" ON "intended_course" ("Program_Code");
CREATE INDEX "idx_pay_student" ON "payment" ("student_id");
CREATE INDEX "idx_pay_semester" ON "payment" ("semester_id");
CREATE INDEX "idx_pay_year" ON "payment" ("year_id");
CREATE INDEX "idx_prog_college" ON "programs" ("college_id");
CREATE INDEX "idx_rec_payment" ON "receipt" ("payment_id");
CREATE INDEX "idx_sch_subject" ON "schedule" ("subject_id");
CREATE INDEX "idx_sch_instructor" ON "schedule" ("instructor_id");
CREATE INDEX "idx_sch_section" ON "schedule" ("section_id");
CREATE INDEX "idx_sch_semester" ON "schedule" ("semester_id");
CREATE INDEX "idx_sch_year" ON "schedule" ("year_id");
CREATE INDEX "idx_sec_program" ON "section" ("program_code");
CREATE INDEX "idx_sec_campus" ON "section" ("campus_id");
CREATE INDEX "idx_spec_program" ON "specializations" ("Program_Code");
CREATE INDEX "idx_sp_college" ON "special_programs" ("college_id");
CREATE INDEX "idx_stu_applicant" ON "students" ("applicant_id");
CREATE INDEX "idx_stu_section" ON "students" ("section_id");
CREATE INDEX "idx_stu_semester" ON "students" ("semester_id");
CREATE INDEX "idx_stu_program" ON "students" ("program_code");
CREATE INDEX "idx_sub_college" ON "subjects" ("College_Id");

ALTER TABLE "admission_info" ADD CONSTRAINT "fk_admission_info_applicants" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "applicant_status_log" ADD CONSTRAINT "fk_asl_applicant" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON DELETE CASCADE;
ALTER TABLE "educational_background" ADD CONSTRAINT "fk_educational_background_applicants" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "enrolled_subjects" ADD CONSTRAINT "fk_enrolled_subjects_enrollment" FOREIGN KEY ("enrollment_id") REFERENCES "enrollment" ("enrollment_id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "enrolled_subjects" ADD CONSTRAINT "fk_enrolled_subjects_instructors" FOREIGN KEY ("instructor_id") REFERENCES "instructors" ("Instructor_ID") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "enrolled_subjects" ADD CONSTRAINT "fk_enrolled_subjects_subjects" FOREIGN KEY ("subject_id") REFERENCES "subjects" ("Subject_Id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "enrollment" ADD CONSTRAINT "fk_enrollment_section" FOREIGN KEY ("section_id") REFERENCES "section" ("section_id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "enrollment" ADD CONSTRAINT "fk_enrollment_semester" FOREIGN KEY ("semester_id") REFERENCES "semester" ("semester_id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "enrollment" ADD CONSTRAINT "fk_enrollment_students" FOREIGN KEY ("student_id") REFERENCES "students" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "enrollment" ADD CONSTRAINT "fk_enrollment_year" FOREIGN KEY ("year_id") REFERENCES "year" ("year_id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "family_info" ADD CONSTRAINT "fk_family_info_applicants" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "grades" ADD CONSTRAINT "fk_grades_enrolled_subjects" FOREIGN KEY ("enrolled_subject_id") REFERENCES "enrolled_subjects" ("enrolled_subject_id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "instructors" ADD CONSTRAINT "fk_instructors_campus" FOREIGN KEY ("Campus_ID") REFERENCES "campus" ("Campus_Id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "instructors" ADD CONSTRAINT "fk_instructors_colleges" FOREIGN KEY ("College_ID") REFERENCES "colleges" ("college_id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "instructors" ADD CONSTRAINT "fk_instructors_subjects" FOREIGN KEY ("Subject_ID") REFERENCES "subjects" ("Subject_Id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "intended_course" ADD CONSTRAINT "fk_intended_course_applicants" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "intended_course" ADD CONSTRAINT "fk_intended_course_programs" FOREIGN KEY ("Program_Code") REFERENCES "programs" ("Program_Code") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "payment" ADD CONSTRAINT "fk_payment_semester" FOREIGN KEY ("semester_id") REFERENCES "semester" ("semester_id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "payment" ADD CONSTRAINT "fk_payment_students" FOREIGN KEY ("student_id") REFERENCES "students" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "payment" ADD CONSTRAINT "fk_payment_year" FOREIGN KEY ("year_id") REFERENCES "year" ("year_id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "programs" ADD CONSTRAINT "fk_programs_colleges" FOREIGN KEY ("college_id") REFERENCES "colleges" ("college_id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "receipt" ADD CONSTRAINT "fk_receipt_payment" FOREIGN KEY ("payment_id") REFERENCES "payment" ("payment_id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "schedule" ADD CONSTRAINT "fk_schedule_instructors" FOREIGN KEY ("instructor_id") REFERENCES "instructors" ("Instructor_ID") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "schedule" ADD CONSTRAINT "fk_schedule_section" FOREIGN KEY ("section_id") REFERENCES "section" ("section_id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "schedule" ADD CONSTRAINT "fk_schedule_semester" FOREIGN KEY ("semester_id") REFERENCES "semester" ("semester_id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "schedule" ADD CONSTRAINT "fk_schedule_subjects" FOREIGN KEY ("subject_id") REFERENCES "subjects" ("Subject_Id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "schedule" ADD CONSTRAINT "fk_schedule_year" FOREIGN KEY ("year_id") REFERENCES "year" ("year_id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "section" ADD CONSTRAINT "fk_section_campus" FOREIGN KEY ("campus_id") REFERENCES "campus" ("Campus_Id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "section" ADD CONSTRAINT "fk_section_programs" FOREIGN KEY ("program_code") REFERENCES "programs" ("Program_Code") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "specializations" ADD CONSTRAINT "fk_specializations_programs" FOREIGN KEY ("Program_Code") REFERENCES "programs" ("Program_Code") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "special_programs" ADD CONSTRAINT "fk_special_programs_colleges" FOREIGN KEY ("college_id") REFERENCES "colleges" ("college_id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "students" ADD CONSTRAINT "fk_students_applicants" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "students" ADD CONSTRAINT "fk_students_programs" FOREIGN KEY ("program_code") REFERENCES "programs" ("Program_Code") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "students" ADD CONSTRAINT "fk_students_section" FOREIGN KEY ("section_id") REFERENCES "section" ("section_id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "students" ADD CONSTRAINT "fk_students_semester" FOREIGN KEY ("semester_id") REFERENCES "semester" ("semester_id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "subjects" ADD CONSTRAINT "fk_subjects_colleges" FOREIGN KEY ("College_Id") REFERENCES "colleges" ("college_id") ON DELETE SET NULL ON UPDATE CASCADE;